import Head from "next/head";
import { useEffect, useState } from "react";
import Card from "../components/containers/Card";
import { useAuth } from "../context/AuthContext";
import { useRouter } from "next/router";
import { collection, getDocs, doc, getDoc } from "firebase/firestore";
import { db } from "../config/firebase";
import loadCustomRoutes from "next/dist/lib/load-custom-routes";

export default function Home() {
  // User obj
  const { user, logout } = useAuth();
  // Router
  const router = useRouter();
  // State to store debatts
  const [debatts, setDebatts] = useState([]);
  const [numberPosts, setNumberPosts] = useState(23);

  // Fetch Debatts
  const fetchDebatts = async () => {
    const querySnapshot = await getDocs(collection(db, "Debatts"));
    const debattsArr = [];
    querySnapshot.forEach((doc) => {
      debattsArr.push(doc.data());
    });
    debattsArr.sort((a, b) => {
      var dateA = new Date(a.createdAt);
      var dateB = new Date(b.createdAt);

      return dateA < dateB ? 1 : -1;
    });
    setDebatts(debattsArr);
  };

  // Check if user is banned
  const checkBannedUser = async () => {
    if (user) {
      const docRef = doc(db, "Users", user?.displayName);
      const docSnap = await getDoc(docRef);

      if (docSnap.exists()) {
        if (docSnap.data().banned && docSnap.data().banned !== undefined) {
          alert("You are banned");
          logout();
        }
      } else {
        console.log("No such document!");
      }
    }
  };

  // Handle Load More Posts
  const loadMorePosts = () => {
    setNumberPosts((prevValue) => prevValue + 10);
  };

  useEffect(() => {
    checkBannedUser();
    fetchDebatts();
  }, []);

  return (
    <div>
      <Head>
        <title>Debatts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Home */}
      <main>
        {debatts.slice(0, numberPosts).map((e, i) => {
          return (
            <Card
              key={i}
              title={e.title}
              body={e.body}
              id={e.title}
              wide={i == 0}
              author={e.author}
              createdAt={e.createdAt}
            />
          );
        })}
      </main>

      {/* Load More Posts Button */}
      {debatts.length > 23 && debatts.length >= numberPosts && (
        <div className="flex justify-center align-center mb-6">
          <button
            className="transition ease-in-out duration-250 bg-transparent hover:bg-blue-700 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-700 hover:border-transparent rounded"
            onClick={loadMorePosts}
          >
            Load More
          </button>
        </div>
      )}
    </div>
  );
}
