import Head from "next/head";
import { useEffect, useState } from "react";
import Card from "../components/containers/Card";
import { useAuth } from "../context/AuthContext";
import { useRouter } from "next/router";
import { collection, getDocs, doc, getDoc } from "firebase/firestore";
import { db } from "../config/firebase";

export default function Home() {
  // User obj
  const { user, logout } = useAuth();
  // Router
  const router = useRouter();
  // State to store debatts
  const [debatts, setDebatts] = useState([]);

  const fetchDebatts = async () => {
    const querySnapshot = await getDocs(collection(db, "Debatts"));
    const debattsArr = [];
    querySnapshot.forEach((doc) => {
      debattsArr.push(doc.data());
    });
    setDebatts(debattsArr);
  };

  const checkBannedUser = async () => {
    if (user) {
      const docRef = doc(db, "Users", user?.displayName);
      const docSnap = await getDoc(docRef);

      if (docSnap.exists()) {
        if (docSnap.data().banned && docSnap.data().banned !== undefined) {
          alert("You are banned");
          logout();
        }
      } else {
        console.log("No such document!");
      }
    }
  };

  useEffect(() => {
    checkBannedUser();
    fetchDebatts();
  }, []);

  return (
    <div>
      <Head>
        <title>Debatts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Home */}
      <main>
        {debatts.map((e, i) => {
          return (
            <Card
              key={i}
              title={e.title}
              body={e.body}
              id={e.title}
              wide={i == 0}
              author={e.author}
              createdAt={e.createdAt}
            />
          );
        })}
      </main>
    </div>
  );
}
